# NumPy 

* NumPy is a linear algebra library. 
* NumPy is the most popular data science library as most other python libraries that work with data use NumPy as a building block.
* NumPy arrays are the most essential for this course. NumPy arrays contain two types, namely: Vectors (1D Arrays) and Matrices (2D Arrays)

### Installation instructions
 **If you use the Anaconda distribution, use the following command to install NumPy by typing the command below in your terminal or in your command prompt.**
 
  *conda install numpy*
 
 **If you are not using Anaconda for python then check the official documentation of NumPy to understand how you can install it** 
 
 [NumPy Installation Instructions](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)

**To understand why you would want to choose NumPy array as a way to store your data over using Lists, check out this uber cool**
[StackOverflow Post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists)

## Using NumPy
**Once you have NumPy installed, you can import it using the following command.**

In [103]:
# Note that python is case sensitive and only accepts lower case for the word 'NumPy'
import numpy as np

### Creating a NumPy Array
We can create a NumPy array by casting a list or list of lists.

In [104]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [105]:
arr = np.array(my_list)
arr

array([1, 2, 3])

This is a one dimensional array. If we want to create a two dimensional array,then we need to use multiple lists. 

In [106]:
mat = [[1,2,3],[4,5,6],[7,8,9]]
mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [107]:
# To convert this list of lists into an array we can cast this list to an array
arr_mat = np.array(mat)
arr_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

The two sets of brackets indicate that this is a two dimensional array.

We will not be using this method very frequently to create NumPy arrays, instead we will be using NumPy's built in functions to create arrays.

#### Built in methods to create a NumPy array
* Using arange
* Using zeroes and ones
* Using linspace
* Using eye or identity matrix
* Using rand or random

#### arange()
Arange returns evenly spaced values within a specified interval

In [108]:
# Using SHIFT+TAB function of the IDE we can see that the function takes a start and stop value for the range
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
# We can mention the step size and jump along the step size in the given range
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

#### Zeros and Ones
Generates an array of zeros and ones.

In [110]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [111]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [112]:
# To specify a 2D array we must enclose the dimensions of the matrix within two parenthesis'
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [113]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Linspace
Returns evenly spaced numbers over a specified interval.

In [114]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [115]:
# How is Linspace different from arange?
# Arange takes a start and stop and a given step size. 
# Linspace takes in a third argument of how many points you want. 
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

Note that this a one dimensional array since it has only one pair of brackets.

#### eye
Returns an identity matrix (A square matrix with all diagonal elements as 1 and the rest of the matrix as 0)

In [116]:
#The digit specified in the function determines the number of rows and columns of the square matrix. 
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Identity matrices can only be two dimensional.

#### Random
NumPy has various ways to create an array of random numbers.

#### rand
Creates an array of the given shape and populates it with
random samples from a uniform distribution
over ``[0, 1)``.

In [117]:
np.random.rand(5)

array([0.39345245, 0.11642037, 0.0337788 , 0.98080288, 0.65782178])

In [118]:
# We need not use a tuple for this function
np.random.rand(5,5)

array([[0.32983825, 0.31091702, 0.1707833 , 0.2048474 , 0.34913361],
       [0.86077761, 0.72545204, 0.35622598, 0.6554535 , 0.04756591],
       [0.65026309, 0.76181115, 0.29093674, 0.56928681, 0.81665684],
       [0.61354855, 0.51209281, 0.98604667, 0.87934171, 0.49039711],
       [0.00935959, 0.32429983, 0.24879315, 0.85452973, 0.56780415]])

#### randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform

In [119]:
# The randn function is a norma distribution centered around 0  
# The rand function uses uniform distribution that is centered around 0 to 1
np.random.randn(2)

array([-0.52004572, -1.11763593])

In [120]:
# We can even create a 2D array as follows
np.random.randn(5,5)

array([[-0.26780898, -0.89912334, -0.15024726,  1.2163104 , -0.11990018],
       [ 0.39516708, -1.14609983, -1.22263104, -0.19988603, -0.49703246],
       [ 0.18240261,  0.58778275,  0.00322191, -0.46087727,  0.67025229],
       [-0.62230954,  0.25244504,  0.75016651, -2.00232855,  1.27662017],
       [-1.67446583,  0.19084667, -1.40666702,  0.06132501, -0.22412682]])

#### randint
Returns a random integer from an inclusive low and exclusive high.

In [121]:
np.random.randint(1,100)

76

In [122]:
# We can even specify how many elements we want
np.random.randint(1,100,10)

array([98, 61, 36, 89, 92, 28, 34, 41, 56, 50])

### Array Attributes and Methods

In [123]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [124]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 7, 42, 25, 12,  4, 30, 38,  1, 41, 41])

#### Reshape
Returns an array of the same samples in a new shape.

In [125]:
# Let us call the same variable with a different shape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**Note that you will receive an error if you do not have enough elements to fill in the new shape of the array.**

In [126]:
arr.reshape(5,10)

ValueError: cannot reshape array of size 25 into shape (5,10)

An easy way to ensure that this error does not occur is to check if the row times the column is equal to the total number of elements.

#### min, max, argmin, argmax
These are useful methods to find the min, max and their index locations. 

In [127]:
ranarr

array([ 7, 42, 25, 12,  4, 30, 38,  1, 41, 41])

In [128]:
ranarr.min()

1

In [129]:
ranarr.max()

42

In [130]:
# Returns the position of the minimum value in the array
ranarr.argmin()

7

In [131]:
# Returns the position of the maximum value in the array
ranarr.argmax()

1

#### Shape
Shape is an attribute of the arrays. Note that this is not a method.

In [132]:
ranarr.shape

(10,)

In [133]:
arr = ranarr.reshape(2,5)
arr

array([[ 7, 42, 25, 12,  4],
       [30, 38,  1, 41, 41]])

In [134]:
arr.shape

(2, 5)

#### dtype
Returns the data type of the array

In [135]:
arr.dtype

dtype('int64')