## NumPy Indexing and Selection

In [122]:
import numpy as np

In [123]:
# Creating a sample array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Bracketing and selection
The simplest way to pick up elements from an array is very similar to picking elements from lists in python.

In [124]:
# Fetching the value at an index
arr[8]

8

In [125]:
# Fetching values in a range
arr[2:5]

array([2, 3, 4])

In [126]:
arr[:5]

array([0, 1, 2, 3, 4])

### Broadcasting
NumPy arrays are different from lists because of their ability to broadcast.

In [127]:
# Setting a value with an index range
# The value 100 is broadcasted to the first three elements in this case
arr[0:3] = 100
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [128]:
# Reset the array, we will understand the importance of this step further..
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [129]:
# Let us see how slicing works on an array
slice_of_arr = arr[:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [130]:
# Let us broadcast the value 99 to the sliced array
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [131]:
# Now if we check the original array, the values in it have also changed
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

This means that the data is not copied onto a new array whereas it is only the view to the original array. Which is why the values in the original array also change when you change the values in the sliced array.

NumPy does this to avoid memory issues with very large arrays.

**If you want to actually create a copy of the original array, then we can use the following method:**

In [132]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

### Indexing a 2D array or matrix
The general format is **array[row][col]** or **array[row,col]**. 

In [133]:
arr_2d = np.array([[10,21,23],[42,15,26],[23,51,17]])
arr_2d

array([[10, 21, 23],
       [42, 15, 26],
       [23, 51, 17]])

In [134]:
# Indexing a row
arr_2d[1]

array([42, 15, 26])

In [135]:
# Fetching an individual value
arr_2d[1][2]

26

In [136]:
arr_2d[1,2]

26

In [137]:
# 2D array slicing
arr_2d

array([[10, 21, 23],
       [42, 15, 26],
       [23, 51, 17]])

In [138]:
# Let us say we want to fetch the 2x2 matrix in the top right corner
arr_2d[:2,1:]

array([[21, 23],
       [15, 26]])

In [139]:
arr_2d[1:,:2]

array([[42, 15],
       [23, 51]])

### Selection
Let us now see how selection can be performed with the help of brackets based on comparison operators.

In [140]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [141]:
# Let us use the greater than operator to see what the array returns
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [142]:
# Let us now assign the boolean values to a variable
bool_arr = arr > 4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [143]:
# This fetches only the elements that hold true for the above condition
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [144]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [145]:
# We can even use variables for the conditional operations
x = 3
arr[arr>x]

array([ 4,  5,  6,  7,  8,  9, 10])

In [146]:
# Exercise
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Now grab chunks of this array using indexing and selection methods.