## NumPy Operations
* Array with Array operations
* Array with Scalar 
* Universal Array Functions

### Arithmetic Operations
We can perform arithmetic operations on array with array or array with scalar easily.

In [40]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [43]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
# Note that we receive a warning on attempting to divide by zero. NumPy replaces that element with a nan(not a number)
arr / arr

<ipython-input-44-20bb9d9f4f6f>:2: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [45]:
# This returns an infinity with a warning and places the other values correctly 
1/arr

<ipython-input-45-2190a4076a9a>:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [46]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

### Universal Array functions
Numpy comes with many universal functions that you can check out [here](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. 

In [47]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# Calculating square roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [49]:
# Calculation the exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [50]:
# Calculating the maximum element
np.max(arr) #Same as arr.max()

9

In [51]:
# We can even perform trigonometric functions on the array
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [52]:
# Logarithmic function on the array
# Note that this returns a warning because of the value '-inf'
np.log(arr)

<ipython-input-52-72e17735d656>:3: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])